### ISSUE TITLE
Explore genetic demultiplexing

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#127]
You may want to also add genetic demultiplexing as a complementary approach (or a ticket to have it as a possibility) if folks multiplexed samples. It may also reveal if there are free-floating nucleic acids around from one or more of the samples (genetic demultiplexing will fail on many cells with a mixture but cell hashing won't necessarily). I don't think this is a breaking issue (cell hashing _should_ be better unless the samples have some significant fraction of compromised tissue, in which case you'd just be filtering "cells" that ended up as a mixture with genetic demultiplexing.

_Originally posted by @cgreene in https://github.com/AlexsLemonade/scpca-nf/issues/9#issuecomment-899657426_

Reference paper (with a workflow we could adapt from): https://www.biorxiv.org/content/10.1101/2020.11.06.371963v3

**Comment by jashapiro** [comment]
I am starting to work on this, and wanted to outline some of the steps... 

- First, we need a set of bulk samples for a reference data set. (In theory we can demux without that, but then assigning to a particular sample is problematic.
- We map each bulk sample (using STAR) to get a BAM file.
- The BAM files are then used with bcftools to call a set of SNPs, stored as a vcf (one per multiplexed set?)

Once we have the VCF in hand, we move to the single-cell portion
- The multiplexed single-cell samples are mapped with CellRanger (maybe we can substitute STARsolo here?)
- We call SNPs per cell with cellSNP/cellSNP-lite https://cellsnp-lite.readthedocs.io/en/latest/manual.html, using the VCF specific to the set of samples that have been multiplexed.
- Perform demultiplexing with Vireo. https://vireosnp.readthedocs.io/en/latest/

This leave a lot of detail to be filled in, but I hope to make progress by attacking each of these steps separately to start, then slowly stitching them into a more robust workflow.

**Comment by jaclyn-taroni** [comment]
I'm going to go ahead and close this.

**Comment by cgreene** [comment]
Oh - we found genetic demultiplexing to be better than cell hashing (more
recall, high concordance). If of interest, Ariel can share her results.

**Comment by jaclyn-taroni** [comment]
@cgreene my message was a bit terse, but we closed this because we have a completed genetic demultiplexing workflow in this repository (https://github.com/AlexsLemonade/alsf-scpca/tree/main/workflows/genetic-demux), and genetic demultiplexing is included in production (docs: https://scpca.readthedocs.io/en/latest/processing_information.html#genetic-demultiplexing). Nothing left to explore!
