### ISSUE TITLE
Quick comparison of alevin-fry to CellRanger for 5' libraries

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/alsf-scpca#133]
Alevin-fry supports 5' libraries (#79) via changing the library type argument. CellRanger automatically detects whether or not an assay is 5' or 3' based (that was my read of what is also outlined in #79). We should do a brief comparison, using many of the benchmarking functions we already have, to ensure we get reasonably comparable results. 

First step is #131 because that'll take some time!

**Comment by allyhawkins** [comment]
We should perform similar comparisons that we have done previously for benchmarking of 3' samples for the 5' samples. this would include the following steps: 

1.  Restricting the analysis to only cells identified in both Cell Ranger and Alevin-fry 
2. Comparing the distributions of mito content, UMI/cell, and genes detected per cell across both tools for shared cells. 
3. Looking at the correlations of mean gene expression for shared genes. 
4. Identifying the overlap in genes identified by both tools 
5. quick pathway analysis of any genes that are quantified in Cell Ranger, but not quantified in Alevin-fry

Overall, this analysis would follow a similar format to the previous benchmarking that has been done, but would only be comparing 2 5' prime samples that are run on Cell Ranger and through Alevin-fry. 

@jashapiro and @jaclyn-taroni Please let me know if there any metrics that you think are missing from this comparison or may be unnecessary.

**Comment by jashapiro** [comment]
If all of those are easy to include, great, but I would say that I would probably be fine with stopping at step 3 or 4. I expect #5 is going to again be dominated by differences in annotation rather than tool-specific, but I could be surprised.

**Comment by jaclyn-taroni** [comment]
> If all of those are easy to include, great, but I would say that I would probably be fine with stopping at step 3 or 4.

Agree!
