### ISSUE TITLE
Explore cellhash data

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#139]
We have some cellhash data (i.e. https://github.com/AlexsLemonade/ScPCA-admin/issues/203), but the current workflows do not support it. We need to add that support, with methods to be determined. This issue is for exploration of the options for cellhashing, in order to determine which methods to use/support.

Some quick notes/links on methods:
`DropletUtils::hashedDrops` looks pretty simple to implement, especially given our current focus on SCE objects, https://rdrr.io/github/MarioniLab/DropletUtils/man/hashedDrops.html

Other methods are noted and linked in the: `cellhashR` repo https://github.com/BimberLab/cellhashR; I am not sure we necessarily want to use `cellhashR` directly (there seems to be big focus on QC and comparing methods, though a consensus method may not be bad), but there should be ideas there we can build from.

**Comment by jaclyn-taroni** [comment]
Can this be closed?
