### ISSUE TITLE
Explore spatial transcriptomics data 

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/alsf-scpca#143]
Because we have a project that has spatial transcriptomics data, we will need to add a workflow to process the spatial transcriptomics data. Alevin-fry does provide a [tutorial on how to use Alevin-fry with spatial data](https://combine-lab.github.io/alevin-fry-tutorials/2021/af-spatial/) where they use Seurat to incorporate the image data with the Alevin-fry output. It appears that the alignment and quantification is performed the same as we would for single-cell or single-nuclei data with Alevin-fry and the data is loaded into R using the same functions, but they then convert it over to a Seurat object and add in the image data rather than keeping it as a `SingleCellExperiment` object. 

Another option could be to explore using the [`Spanial` package and the `SpatialExperiment` class](https://www.biorxiv.org/content/10.1101/2021.01.27.428431v2.full.pdf) which looks to be an extension of a SCE.

It might also be worth it at this stage to do a quick comparison of using [`spaceranger count`](https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/what-is-space-ranger) from 10X to compare the same metrics that we have compared prior (UMI/cell, genes detected/cell, mean gene expression) and look at the overlay of the image with the counts matrix. I don't foresee any issues with Alevin-fry alignment or quantification, but we should be sure that when we integrate the image it is being done correctly. 

Once we have identified the best method of performing alignment, quantification, image integration, and decided on how best to store the Spatial results, we can incorporate the workflow into `scpca-nf`.

**Comment by jashapiro** [comment]
> Another option could be to explore using the [`Spanial` package and the `SpatialExperiment` class](https://www.biorxiv.org/content/10.1101/2021.01.27.428431v2.full.pdf) which looks to be an extension of a SCE.

Based on no real data, I think I would probably explore this route first. [The SpatialExperiment introduction vignette](https://bioconductor.org/packages/release/bioc/vignettes/SpatialExperiment/inst/doc/SpatialExperiment.html) seems well constructed. And how can you be upset when you see [their image example](https://bioconductor.org/packages/release/bioc/vignettes/SpatialExperiment/inst/doc/SpatialExperiment.html#adding-or-removing-images). It looks like the plotting functions come from [ggspavis](https://bioconductor.org/packages/release/bioc/html/ggspavis.html)

Oh, and there is an "Orchestrating" book: https://lmweber.org/OSTA-book/

It looks to me like `Spaniel` is not using the same data structure, in that the extensions it uses to the SCE object may be different. It may be hard to tell at this point which one will be better supported long term. Spaniel also depends on Seurat, and I am not really sure what the implications of that are.
