### ISSUE TITLE
Compare genetic demultiplexing to cellhash results

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#155]
With the work done so far on #127, we now have some genetic demultiplexing results. The next step is to compare those results in terms of sample assignment to previous results from cellhashing. I had previously done some initial exploration of cellhashing alone in https://github.com/AlexsLemonade/alsf-scpca/blob/jashapiro/explore-cellhash/analysis/quantifier-comparisons/12-cellhash-exploration.Rmd

The next step is to build from those results and add in the genetic demultiplexing results to see how well they agree.  

We have also been sent the nuclei counts for each sample from  the pools, so we can look to see if there is general agreement in sample counts, or whether biases are consistent...

**Comment by jaclyn-taroni** [comment]
I'm going to call this closed now that #165 went in
