### ISSUE TITLE
Single Cell Data QC

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#43]
The current Alevin workflow does not perform any particular QC steps; we have been doing this by hand so far.

We should implement some automated QC!

The simplest version of this would be adding [alevinQC](http://www.bioconductor.org/packages/release/bioc/vignettes/alevinQC/inst/doc/alevinqc.html) to the `run-alevin.nf` workflow. For this to work, the current alevin workflow will need to be modified to include the `--dumpFeatures` flag 

While this is pretty easy, it isn't always as robust as we might like, and does not support cross-library summarization (like MultiQC?), which we might like to add in the future. 

To allow for future flexibility, we should make sure to output the entire AlevinQC report directory, not just the `html` files, so that we may be able to process them later after reading in data tables with `readAlevinQC()` or similar.

**Comment by jaclyn-taroni** [comment]
miQC: https://www.biorxiv.org/content/10.1101/2021.03.03.433798v1

**Comment by cgreene** [comment]
Could be useful for training too. It takes the challenge of picking a threshold for dead cell / debris removal and reframes it as a mixture model. The cases where it doesn't work well are samples where there is not a mixture (i.e., no dead cells/debris or no live ones).

**Comment by jaclyn-taroni** [comment]
Can this be closed?

**Comment by jashapiro** [comment]
Yes, I suppose it is largely superseded by our current QC reports.

**Comment by allyhawkins** [comment]
I would say yes.
