### ISSUE TITLE
Explore --mrna flag in alevin

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#44]
Alevin implements some cell filtering/QC that takes advantage of a list of mRNA genes via the `--mrna` flag. We should explore this a bit to see what it does for us.

The hope is that it can allow us to save some QC steps and filtering later, by eliminating cells with high mtRNA content, which are likely to be dead cells. Unfortunately the [documentation on this feature](https://salmon.readthedocs.io/en/latest/alevin.html#mrna) seems a bit light, so it is unclear from the docs alone what it is doing (aside from using naive Bayes classifier). There is somewhat more detail in the Alevin paper: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1670-y#Sec16 

I am not sure how much AlevinQC #43 shows about the mtRNA stats when they are present: we may want to look at those as well.

**Comment by cgreene** [comment]
> mRNA content, which are likely to be dead cells.

Mitochondrial? Not messenger?

**Comment by jashapiro** [comment]
> > mRNA content, which are likely to be dead cells.
> 
> Mitochondrial? Not messenger?

Of course! I mistyped because the flag is poorly named.

**Comment by jashapiro** [comment]
Closing this because we are not using base alevin, and we will use post-quant filtering.
