### ISSUE TITLE
Support 5' libraries

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/alsf-scpca#79]
In adding our first set of 5' libraries, we started to look at what current tools implement for mapping 5' reads. Quoting from https://github.com/AlexsLemonade/ScPCA-admin/pull/137#pullrequestreview-641296309:

> In looking at cellrangers description, they distinguish whether or not an assay is 5' or 3' based on the number of reads that are mapping in the antisense direction. If the fraction of reads from R2 mapping in the antisense direction is > 2X the reads mapping in the sense direction then they assume its in the 5' direction and proceed with the library like that. So in that case, rather than throwing away antisense reads, they would keep them, is what I'm interpreting from that statement.

We will need to investigate further. Once we decide on next steps, we will want to have workflows that implement those changes for 5' libraries. 

Currently the 5' libraries we have are designated as `10Xv2_5prime` in the technology column of the run table.

*Further notes*: 

Alevin looks like it can support 5' libraries by adjusting the library type argument to `-lISF` , as described here: https://github.com/COMBINE-lab/salmon/issues/439#issuecomment-547208043 It certainly seems that that 5' libraries are still stranded, so this should work, though the caveat in that comment makes me wonder a bit.

**Comment by allyhawkins** [comment]
Interesting about changing the library type argument. I do wonder how that would effect mapping and if you would lose a significant amount of information during quantification. It appears that they may have addressed this issue and added in the fiveprime feature to the develop branch? 
https://github.com/ebi-gene-expression-group/scxa-droplet-quantification-workflow/pull/10

It might be worth reaching out to them and seeing what they say about using it with 5'.

**Comment by jashapiro** [comment]
> It appears that they may have addressed this issue and added in the fiveprime feature to the develop branch?
> [ebi-gene-expression-group/scxa-droplet-quantification-workflow#10](https://github.com/ebi-gene-expression-group/scxa-droplet-quantification-workflow/pull/10)

That is a different group that is using the software, not salmon development itself.
